name: deploy changes

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions: write-all
        strategy:
            matrix:
                node-version: [18]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            # - name: Use pnpm
            #   uses: pnpm/action-setup@v2.2.4
            #   with:
            #       version: 7

            # - name: Use Node.js ${{ matrix.node-version }}
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: ${{ matrix.node-version }}
            #       cache: pnpm

            # - name: Install dependencies
            #   run: pnpm install

            # - name: Build project
            #   run: pnpm run build

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: unnecessary
                  config: |
                      User root
                      Port ${{ secrets.SSH_PORT }}

            - name: Adding known_hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

            - name: Remove old deploy
              run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} rm -rf ${{ secrets.TARG_DIR }}

            - name: Deploy with rsync
              run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARG_DIR }} --exclude-from 'exclude.txt' -e "ssh -p ${{ secrets.SSH_PORT }}"

            - name: Start / Restart PM2
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  port: ${{ secrets.SSH_PORT }} # default 22
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      export PATH=$PATH:/root/.nvm/versions/node/v17.4.0
                      pm2 list
                      pm2 delete all
                        cd ${{ secrets.TARG_DIR }}
                        pm2 start ecosystem.config.js
